# Generated by Django 4.1.2 on 2022-10-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм номер или username')),
                ('phone_number', models.CharField(max_length=80, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.AddField(
            model_name='applicant',
            name='course',
            field=models.CharField(choices=[('sat', 'SAT'), ('ielts', 'IELTS')], default='sat', max_length=25, verbose_name='Курс'),
        ),
    ]
